export type TrueEndingStoryCard = {
  id: string;
  speaker: string;
  text: string;
  eyebrow: string;
  leftLabel: string;
  rightLabel: string;
};

export const trueEndingStoryCards: TrueEndingStoryCard[] = [
  {
    id: "true-ending-familiar-room",
    speaker: "나",
    eyebrow: "낯익은 방",
    text: "기억이 난다.\n여긴... 내 자취방이다.",
    leftLabel: "알고 싶지 않아",
    rightLabel: "여긴 어디지?",
  },
  {
    id: "true-ending-dark-room",
    speaker: "기억",
    eyebrow: "꺼진 방",
    text: "불은 꺼져 있다.\n책상 위 컵라면은 반쯤 불어 있다.",
    leftLabel: "숨이 막힌다",
    rightLabel: "익숙한 냄새다",
  },
  {
    id: "true-ending-phone",
    speaker: "기억",
    eyebrow: "핸드폰",
    text: "핸드폰 화면이 켜진다.\n알림이 너무 많다.",
    leftLabel: "보고 싶지 않다",
    rightLabel: "확인한다",
  },
  {
    id: "true-ending-document-results",
    speaker: "기억",
    eyebrow: "서류 결과",
    text: "\"아쉽지만...\"\n\"뛰어난 역량에도 불구하고...\"\n\n전부 같은 말이다.",
    leftLabel: "이제 그만",
    rightLabel: "또 떨어졌구나",
  },
  {
    id: "true-ending-unread-messages",
    speaker: "엄마",
    eyebrow: "읽지 않은 문자",
    text: "엄마에게 문자가 와 있다.\n\n\"밥은 먹었어?\"\n\"전화 한 번만 줘.\"",
    leftLabel: "답장 못 하겠어",
    rightLabel: "미안해",
  },
  {
    id: "true-ending-friend-message",
    speaker: "친구",
    eyebrow: "친구의 문자",
    text: "친구에게도 문자가 와 있다.\n\n\"야, 살아있냐?\"\n\"내일 시간 되면 보자.\"",
    leftLabel: "나갈 힘이 없어",
    rightLabel: "고마운데",
  },
  {
    id: "true-ending-reply-box",
    speaker: "나",
    eyebrow: "답장창",
    text: "답장창에 글자를 쓴다.\n\n\"나 괜찮아.\"\n\n지우고 다시 쓴다.\n\n\"미안.\"\n\n그것도 지운다.",
    leftLabel: "괜찮은 척도 힘들다",
    rightLabel: "아무 말도 못 하겠다",
  },
  {
    id: "true-ending-silent-room",
    speaker: "기억",
    eyebrow: "조용한 방",
    text: "방이 너무 조용하다.\n세상에서 나만 멈춘 것 같다.",
    leftLabel: "누가 알아줬으면",
    rightLabel: "아무도 몰랐으면",
  },
  {
    id: "true-ending-mirror",
    speaker: "나",
    eyebrow: "거울",
    text: "거울 속 얼굴이 낯설다.\n언제부터 이렇게 지쳐 있었을까.",
    leftLabel: "보기 싫다",
    rightLabel: "내가 맞나?",
  },
  {
    id: "true-ending-desk-note",
    speaker: "기억",
    eyebrow: "책상 위 메모",
    text: "메모지가 보인다.\n\n\"이번엔 꼭 붙자.\"\n\"조금만 더 버티자.\"",
    leftLabel: "충분하지 않았나 봐",
    rightLabel: "열심히 했는데",
  },
  {
    id: "true-ending-old-dream",
    speaker: "나",
    eyebrow: "오래된 꿈",
    text: "어릴 때는 되고 싶은 게 많았다.\n지금은 내일이 오는 것도 무섭다.",
    leftLabel: "다 사라졌어",
    rightLabel: "나도 꿈이 있었지",
  },
  {
    id: "true-ending-last-thought",
    speaker: "나",
    eyebrow: "마지막 생각",
    text: "나는 사라져도 괜찮을 거라고 생각했다.\n아무도 크게 달라지지 않을 거라고.",
    leftLabel: "정말 그럴까?",
    rightLabel: "그럴 리 없어",
  },
  {
    id: "true-ending-true-heart",
    speaker: "나",
    eyebrow: "진짜 마음",
    text: "하지만 그건 죽고 싶다는 뜻이 아니었다.\n\n그냥,\n혼자 버티고 싶지 않았다.",
    leftLabel: "나 너무 힘들어",
    rightLabel: "살려줘",
  },
  {
    id: "true-ending-blue-fog",
    speaker: "기억",
    eyebrow: "푸른 안개",
    text: "방 안에 푸른 안개가 번진다.\n누군가 천천히 걸어온다.",
    leftLabel: "무서워",
    rightLabel: "누구야?",
  },
  {
    id: "true-ending-cheongryeong-chasa",
    speaker: "청령차사",
    eyebrow: "청령차사",
    text: "청령차사가 나를 내려다본다.\n\n\"드디어 기억났나.\"",
    leftLabel: "나를 알아?",
    rightLabel: "당신은...",
  },
  {
    id: "true-ending-chasa-words",
    speaker: "청령차사",
    eyebrow: "차사의 말",
    text: "\"네가 도와주던 영혼들.\"\n\n\"그 아이들은 모두,\n네가 외면한 너였다.\"",
    leftLabel: "내가... 나를?",
    rightLabel: "그럴 리 없어",
  },
  {
    id: "true-ending-memory-shards",
    speaker: "기억",
    eyebrow: "기억 조각",
    text: "스쳐 지나간다.\n\n면접장 앞에서 떨던 영혼.\n돈이 없어 밥을 굶던 영혼.\n친구 연락을 피하던 영혼.\n밤새 울던 영혼.\n\n전부 나였다.",
    leftLabel: "몰랐으면 했어",
    rightLabel: "알고 있었어",
  },
  {
    id: "true-ending-chasa-gaze",
    speaker: "청령차사",
    eyebrow: "차사의 시선",
    text: "청령차사는 꾸짖지 않았다.\n그저 조용히 옆에 앉았다.",
    leftLabel: "화 안 내?",
    rightLabel: "왜 아무 말 안 해?",
  },
  {
    id: "true-ending-chasa-answer",
    speaker: "청령차사",
    eyebrow: "청령차사의 대답",
    text: "\"이미 충분히 혼났잖아.\"\n\n\"네가 너한테.\"",
    leftLabel: "미안해",
    rightLabel: "......",
  },
  {
    id: "true-ending-why-broke",
    speaker: "청령차사",
    eyebrow: "무너진 이유",
    text: "\"너는 약해서 무너진 게 아니다.\"\n\n\"너무 오래,\n혼자 강한 척해서 무너진 거다.\"",
    leftLabel: "기대고 싶었어",
    rightLabel: "혼자여야 했어",
  },
  {
    id: "true-ending-phone-rings-again",
    speaker: "엄마",
    eyebrow: "다시 울리는 핸드폰",
    text: "핸드폰이 다시 울린다.\n\n엄마: 답장 안 해도 돼.\n그냥 살아만 있어줘.",
    leftLabel: "미안해",
    rightLabel: "엄마...",
  },
  {
    id: "true-ending-friend-new-message",
    speaker: "친구",
    eyebrow: "친구의 새 문자",
    text: "친구: 야.\n내일 네 집 앞에 간다.\n\n친구: 싫어도 문은 열어라.",
    leftLabel: "고맙다",
    rightLabel: "바보 같네",
  },
  {
    id: "true-ending-hand",
    speaker: "나",
    eyebrow: "손",
    text: "손이 떨린다.\n하지만 핸드폰을 놓지 않는다.",
    leftLabel: "아직 무서워",
    rightLabel: "답장한다",
  },
  {
    id: "true-ending-first-sentence",
    speaker: "나",
    eyebrow: "첫 문장",
    text: "답장창에 아주 천천히 쓴다.\n\n\"나 좀 힘들어.\"",
    leftLabel: "지우지 않는다",
    rightLabel: "보낸다",
  },
  {
    id: "true-ending-sent",
    speaker: "나",
    eyebrow: "전송",
    text: "메시지가 전송된다.\n\n아무것도 해결되지 않았다.\n그런데 이상하게 숨이 조금 쉬어진다.",
    leftLabel: "조금만 더",
    rightLabel: "아직 살아있다",
  },
  {
    id: "true-ending-chasa-hand",
    speaker: "청령차사",
    eyebrow: "청령차사의 손",
    text: "청령차사가 손을 내민다.\n\n\"잘했다.\"\n\n\"합격보다 어려운 걸 했구나.\"",
    leftLabel: "정말?",
    rightLabel: "이게 뭐가...",
  },
  {
    id: "true-ending-chasa-smile",
    speaker: "청령차사",
    eyebrow: "차사의 미소",
    text: "\"도움을 청하는 건 약한 일이 아니다.\"\n\n\"살겠다고 말하는 일이지.\"",
    leftLabel: "도와줘",
    rightLabel: "살고 싶어",
  },
  {
    id: "true-ending-morning",
    speaker: "나",
    eyebrow: "아침",
    text: "창문 틈으로 아침빛이 들어온다.\n방은 여전히 엉망이다.\n\n하지만 끝난 건 아니었다.",
    leftLabel: "먼저 전화부터",
    rightLabel: "정리해볼까",
  },
  {
    id: "true-ending-last-memory",
    speaker: "나",
    eyebrow: "마지막 기억",
    text: "나는 그날 합격하지 못했다.\n대단한 사람이 된 것도 아니었다.\n\n그저 처음으로,\n나를 혼자 두지 않았다.",
    leftLabel: "다시 시작하자",
    rightLabel: "괜찮아",
  },
  {
    id: "true-ending-saved-myself",
    speaker: "나",
    eyebrow: "엔딩 문구",
    text: "그날 이후로도\n힘든 날은 계속 있었다.\n\n하지만 나는 알게 되었다.\n\n사람은 혼자 무너지지만,\n다시 일어날 때는 누군가의 손을 잡아도 된다는 걸.",
    leftLabel: "나를 구한 사람",
    rightLabel: "끝",
  },
];
